SITE_1337X = '1337x'
SITE_RARBG = 'rarbg'

CATEGORY_MOVIES = 'movies'
CATEGORY_TV_SHOWS = 'tv shows'
CATEGORY_GAMES = 'games'

SUBCATEGORY_DVD = 'dvd'
SUBCATEGORY_H264 = 'h.264/x264'
SUBCATEGORY_HEVC = 'HEVC/x265'
SUBCATEGORY_BOLLYWOOD = 'bollywood'
SUBCATEGORY_HD_MOVIES = 'hd'
SUBCATEGORY_DUBS = 'dubs'
SUBCATEGORY_UHD = 'uhd'
SUBCATEGORY_DIVX_MOVIES = 'divx'
SUBCATEGORY_MP4 = 'mp4'

SUBCATEGORY_HD_TV = 'hd'
SUBCATEGORY_SD_TV = 'sd'
SUBCATEGORY_DIVX_TV = 'divx'
SUBCATEGORY_HEVC_TV = 'hevc/x265'

SUBCATEGORY_PCGAMES = 'pcgames'
SUBCATEGORY_SWITCH = 'switch'

STATUS_NEW = 10
STATUS_SKIPPED = 20
STATUS_FINISHED = 30