SITE_1337X = '1337x'
SITE_RARBG = 'rarbg'

CATEGORY_MOVIES = 'movies'
CATEGORY_TV_SHOWS = 'tv shows'
CATEGORY_GAMES = 'games'

SUBCATEGORY_H264 = 'h.264/x264'
SUBCATEGORY_HEVC = 'HEVC/x265'
SUBCATEGORY_BOLLYWOOD = 'bollywood'
SUBCATEGORY_HD = 'hd'
SUBCATEGORY_DUBS = 'dubs'
SUBCATEGORY_PCGAMES = 'pcgames'
SUBCATEGORY_SWITCH = 'switch'

STATUS_NEW = 10
STATUS_SKIPPED = 20
STATUS_FINISHED = 30
