# Generated by Django 4.0.6 on 2022-11-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(choices=[('1337x', '1337x')], max_length=100)),
                ('category', models.CharField(choices=[('movies', 'movies'), ('tv shows', 'tv shows'), ('games', 'games')], max_length=100)),
                ('subcategory', models.CharField(choices=[('h.264/x264', 'h.264/x264'), ('bollywood', 'bollywood'), ('pcgames', 'pcgames')], max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250, unique=True)),
                ('seeders', models.IntegerField()),
                ('leechers', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('uploader', models.CharField(max_length=250)),
                ('pirate', models.CharField(blank=True, max_length=250, null=True)),
                ('video_codec', models.CharField(blank=True, max_length=250, null=True)),
                ('audio_codec', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('resolution', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrents', to='main.title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TorrentReady',
            fields=[
            ],
            options={
                'verbose_name': 'Ready',
                'verbose_name_plural': 'Readies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.torrent',),
        ),
    ]
