# Generated by Django 4.0.6 on 2022-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('skipped', 'skipped'), ('finished', 'finished')], default='new', max_length=50),
        ),
    ]
