# Generated by Django 4.0.6 on 2022-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_title_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TorrentReady',
        ),
        migrations.CreateModel(
            name='TitleReady',
            fields=[
            ],
            options={
                'verbose_name': 'Ready',
                'verbose_name_plural': 'Readies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.title',),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.IntegerField(choices=[(10, 'New'), (20, 'Skipped'), (30, 'Finished')], default=10, max_length=50),
        ),
    ]
