# Generated by Django 4.0.6 on 2022-12-18 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_torrentready_titleready_alter_title_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('text',)},
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.IntegerField(choices=[(10, 'New'), (20, 'Skipped'), (30, 'Finished')], default=10),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='site',
            field=models.CharField(choices=[('1337x', '1337x'), ('rarbg', 'rarbg')], max_length=100),
        ),
    ]
