# Generated by Django 4.0.6 on 2023-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_expansion_alter_title_options_title_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='series',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
