# Generated by Django 4.0.6 on 2024-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_delete_titleready_movies_pcgames_tvshows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='earliest_upload_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='latest_upload_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
