# Generated by Django 5.0.3 on 2025-06-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_remove_torrent_status_at_title_status_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(unique=True)),
                ('area', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('km', models.FloatField()),
                (
                    'postcode_a',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='distances_a',
                        to='main.postcode',
                    ),
                ),
                (
                    'postcode_b',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='distances_b',
                        to='main.postcode',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['postcode_a'], name='main_distan_postcod_c60ae2_idx'),
                    models.Index(fields=['postcode_b'], name='main_distan_postcod_8c78ad_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='distance',
            constraint=models.UniqueConstraint(
                fields=('postcode_a', 'postcode_b'), name='unique_distance_pair'
            ),
        ),
    ]
