# Generated by Django 5.0.3 on 2025-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_postcode_distance_distance_unique_distance_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='level',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcode',
            name='opencage',
            field=models.BooleanField(default=False),
        ),
    ]
